spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    useSSL: false
    characterEncoding: UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    converters:
      preferred-json: gson
  jpa:
    database: mysql
    database-platform: ru.mirea.data.LocalMysqlDialect
    hibernate.ddl-auto: create-drop

hibernate:
  connection:
    useUnicode: true
    characterEncoding: utf8
    CharSet: utf8